@APIBanco_HostAddress = http://localhost:5260

GET {{APIBanco_HostAddress}}/api/clients/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjIiLCJzdWIiOiIyMS8wMy8yMDI0IDAwOjAwOjAwIiwiZW1haWwiOiJ1c2VyMTExQGV4YW1wbGUuY29tIiwianRpIjoiNWQyOWRiN2UtZWE0ZC00ODBiLTliNTgtZjZlZWY3YzYyMzFjIiwibmJmIjoxNzExMDU2MTIzLCJleHAiOjE3MTEwNTk3MjMsImlhdCI6MTcxMTA1NjEyM30.kn2mgByP6nP0JqB5Mwc26xJXvk5q57d1WEpixebO2rM
Accept: application/json

###
