@APIBanco_HostAddress = http://localhost:5260

GET {{APIBanco_HostAddress}}/api/clients/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjEiLCJDcGYiOiIxMTExMTExMTExMSIsInN1YiI6IjI5LzEyLzIwMTMgMDA6MDA6MDAiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImp0aSI6ImY5MmIyODA5LTM0MzctNGFiMy05YTA2LTE5YWFmMzhjNDMyZSIsIm5iZiI6MTcxMTMwODA0MywiZXhwIjoxNzExMzExNjQzLCJpYXQiOjE3MTEzMDgwNDN9.sQJllb0-NRSW14s3OHgdB1xW6HXkIWnZDoZUBt1lMr8
Accept: application/json

###

POST {{APIBanco_HostAddress}}/api/clients/login
Accept: application/json
content-type: application/json

{
  "cpf": "98242755858",
  "password": "Password1234@"
}

###

POST {{APIBanco_HostAddress}}/api/clients/login
Accept: application/json
content-type: application/json

{
  "cpf": "56173967609",
  "password": "Password1234@"
}

###

POST {{APIBanco_HostAddress}}/api/clients/login
Accept: application/json
content-type: application/json

{
  "cpf": "11111111111",
  "password": "Password1234@"
}

###

POST {{APIBanco_HostAddress}}/api/clients/login
Accept: application/json
content-type: application/json

{
  "cpf": "22222222222",
  "password": "Password1234@"
}

###

GET {{APIBanco_HostAddress}}/api/Transactions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjEiLCJDcGYiOiIxMTExMTExMTExMSIsInN1YiI6IjI5LzEyLzIwMTMgMDA6MDA6MDAiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImp0aSI6ImY5MmIyODA5LTM0MzctNGFiMy05YTA2LTE5YWFmMzhjNDMyZSIsIm5iZiI6MTcxMTMwODA0MywiZXhwIjoxNzExMzExNjQzLCJpYXQiOjE3MTEzMDgwNDN9.sQJllb0-NRSW14s3OHgdB1xW6HXkIWnZDoZUBt1lMr8
Accept: application/json

###