@APIBanco_HostAddress = http://localhost:5260

GET {{APIBanco_HostAddress}}/api/clients/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjIiLCJDcGYiOiIyMjIyMjIyMjIyMiIsInN1YiI6IjI5LzEyLzIwMTMgMDA6MDA6MDAiLCJlbWFpbCI6InRlc3RlZnJvbnRkb2lzQGdtYWlsLmNvbSIsImp0aSI6Ijg2ZWI2NGVhLWUzMjEtNGRiYS1iYTYyLTJkODYyZTgxMjQ5ZSIsIm5iZiI6MTcxMTMxNDAyMCwiZXhwIjoxNzExMzE3NjIwLCJpYXQiOjE3MTEzMTQwMjB9.J4De3aXvfoascbqekJJpVUbpzCJF80HdJ-jplKXWUnI
Accept: application/json

###

POST {{APIBanco_HostAddress}}/api/clients/login
Accept: application/json
content-type: application/json

{
  "cpf": "98242755858",
  "password": "Password1234@"
}

###

POST {{APIBanco_HostAddress}}/api/clients/login
Accept: application/json
content-type: application/json

{
  "cpf": "56173967609",
  "password": "Password1234@"
}

###

POST {{APIBanco_HostAddress}}/api/clients/login
Accept: application/json
content-type: application/json

{
  "cpf": "11111111111",
  "password": "Password1234@"
}

###

POST {{APIBanco_HostAddress}}/api/clients/login
Accept: application/json
content-type: application/json

{
  "cpf": "22222222222",
  "password": "Password1234@"
}

###

GET {{APIBanco_HostAddress}}/api/Transactions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjIiLCJDcGYiOiIyMjIyMjIyMjIyMiIsInN1YiI6IjI5LzEyLzIwMTMgMDA6MDA6MDAiLCJlbWFpbCI6InRlc3RlZnJvbnRkb2lzQGdtYWlsLmNvbSIsImp0aSI6Ijg2ZWI2NGVhLWUzMjEtNGRiYS1iYTYyLTJkODYyZTgxMjQ5ZSIsIm5iZiI6MTcxMTMxNDAyMCwiZXhwIjoxNzExMzE3NjIwLCJpYXQiOjE3MTEzMTQwMjB9.J4De3aXvfoascbqekJJpVUbpzCJF80HdJ-jplKXWUnI
Accept: application/json

###